flowchart LR
    S["1<br/>Source"] --> I["2<br/>Inspect"]
    I --> D["3<br/>Deconstruct"]
    D --> P["4<br/>Prep"]
    P --> DE["5<br/>Design"]
    DE --> C["6<br/>Cut"]
    C --> A["7<br/>Assemble"]
    A --> F["8<br/>Finish"]
    F --> IN["9<br/>Install"]
